# Generated by Django 3.0.6 on 2020-09-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=500)),
                ('creator', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500, null=True)),
                ('description', models.CharField(default='', max_length=5000, null=True)),
                ('topic', models.CharField(default='', max_length=500, null=True)),
                ('identifier', models.CharField(default='', max_length=500, null=True)),
                ('creator', models.CharField(default='', max_length=500, null=True)),
                ('publisher', models.CharField(default='', max_length=500, null=True)),
                ('contributor', models.CharField(default='', max_length=500, null=True)),
                ('access_right', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], default='Other', max_length=50, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('data_format', models.CharField(choices=[('zip', 'zip'), ('csv', 'csv'), ('json', 'json'), ('txt', 'txt'), ('xlsx/xls', 'xlsx/xls')], default='Other', max_length=50, null=True)),
                ('source', models.CharField(choices=[('OpenAire', 'OpenAire'), ('Wikidata', 'Wikidata')], default='Other', max_length=50, null=True)),
                ('issued_date', models.DateField(null=True)),
                ('modified_date', models.DateField(null=True)),
                ('version', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('contact', models.CharField(default='', max_length=500, null=True)),
                ('link', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Link')),
            ],
        ),
    ]
