# Generated by Django 3.0.6 on 2020-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='link',
        ),
        migrations.AddField(
            model_name='dataset',
            name='link',
            field=models.ManyToManyField(default='', to='search.Link'),
        ),
    ]
