# Generated by Django 3.0.6 on 2020-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200923_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
