# Generated by Django 3.0.6 on 2020-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200923_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='version',
        ),
        migrations.AddField(
            model_name='dataset',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
