# Generated by Django 3.0.6 on 2020-09-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200924_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='language',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
