# Generated by Django 3.0.6 on 2020-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200924_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='creator',
        ),
        migrations.AddField(
            model_name='dataset',
            name='referenced_papers',
            field=models.ManyToManyField(default='', to='search.Paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
