# Generated by Django 3.0.6 on 2020-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_dataset_ranking_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='referenced_papers',
        ),
        migrations.AddField(
            model_name='dataset',
            name='referenced_papers',
            field=models.CharField(default='', max_length=10000000, null=True),
        ),
    ]
