# Generated by Django 3.0.6 on 2020-11-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20201116_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
